name: Publish Chatwoot Docker Image to AWS ECR

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your AWS region

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 688351450096.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag reconvin/reconvin-chat:latest

      - name: Tag the Docker image
        run: docker tag reconvin/reconvin-chat:latest 688351450096.dkr.ecr.ap-south-1.amazonaws.com/reconvin/reconvin-chat:latest

      - name: Push to Amazon ECR
        run: docker push 688351450096.dkr.ecr.ap-south-1.amazonaws.com/reconvin/reconvin-chat:latest
